### ISSUE TITLE
Feature Request: Minimum star limit for answers in brainly auto answer

### ISSUE THREAD

**Issue by FermentedSpiderEye** [GSRHackZ/EdgyBot_edgenuity-nuke#11]
Brainly Auto Answer enhancement:
It would be nice to have a setting to enter a minimum star limit for brainly answers, or a high confidence mode
For example, it would autofill a brainly answer with 4.5 stars, but it wouldn't for an answer with 3.2 stars.

Thank you!

**Comment by GSRHackZ** [comment]
We have a function called bestAnswer(). This determines the best answer found by by the auto brainly search and then sends it back to Edgenuity for the user to see if auto answer is off or to be automatically inputted if auto answer is on. Adding a star limit might not be the best solution here, because the ratings for different answers are sometimes completely useless. An incorrect answer can have a 4.0 star rating with only one user leaving a vote, while a correct answer can have a rating of 3.5 with many votes. The bestAnswer() function already calculates all of this. 

What do you think? 🙏

**Comment by FermentedSpiderEye** [comment]
Good idea. In my ideal workflow, I would have the extension automatically fill in the answer for me if it's confident enough (considering stars and votes), and if it's not, it would just show me the answer so I can evaluate it myself. It's a mix of what I'm suggesting and what the bestAnswer() function does.

**Comment by GSRHackZ** [comment]
I will now close this issue (feature request) as completed. You may reopen it if needed. 👌
